- id: latexindent-system
  name: latexindent.pl
  entry: latexindent
  language: system
  types:
    - tex
  description: Run latexindent from system-level executables
  args:
    - "--overwriteIfDifferent"
    - "--silent"
    - "--local"
    - "--yaml=defaultIndent: '  '"
