- id: latexindent-system
  name: latexindent.pl
  entry: latexindent
  language: system
  files: "^((.*.tex)|(.*.sty)|(.*.cls)|(.*.bib))$"
  description: Run latexindent from system-level executables
  args:
    - "--overwriteIfDifferent"
    - "--silent"
    - "--local"
    - "--modifylinebreaks"
    - "--GCString"
- id: shfmt-system
  name: shfmt
  entry: shfmt
  language: system
  types:
    - shell
  exclude_types:
    - zsh
  description: Shell source code formatter from system-level executables
  args:
    - "--write"
    - "--simplify"
    - "--indent"
    - "2"
    - "--case-indent"
    - "--space-redirects"
