name: CI

on:
  push:

env:
  TOOLCHAIN: stable

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        run: |-
          rustup default "${{ env.TOOLCHAIN }}"
          rustup update "${{ env.TOOLCHAIN }}"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: make dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: dist/*
    strategy:
      matrix:
        os:
          - ubuntu-latest

  release:
    name: Release
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs:
      - build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Release
        uses: liblaf/template/.github/actions/release@main
        with:
          tag: dev
          files: "*"
          prerelease: true
